language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
script: bundle exec rake test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libreadline-dev build-essential libxml2-dev libxslt1-dev