language: ruby
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- 1.9.2
- jruby-head
- jruby-19mode
- rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script: bundle exec rake test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libreadline-dev
