language: ruby
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- 1.9.2
- 1.8.7
- jruby-19mode
- jruby-18mode
- rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.8.7
    - rvm: jruby-18mode

script: bundle exec rake test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libreadline-dev build-essential libxml2-dev libxslt1-dev